export const styles = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  title: {
    color: "#2563eb",
    margin: 0,
  },
  button: {
    backgroundColor: "#2563eb",
    color: "white",
    padding: "10px 20px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "14px",
    transition: "background-color 0.2s",
  },
  buttonSuccess: {
    backgroundColor: "#10b981",
  },
  buttonDanger: {
    backgroundColor: "#ef4444",
  },
  buttonWarning: {
    backgroundColor: "#f59e0b",
  },
  buttonSmall: {
    padding: "5px 10px",
    fontSize: "12px",
    marginRight: "5px",
  },
  buttonGroup: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
  },
  form: {
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    marginBottom: "20px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "15px",
  },
  formGroup: {
    marginBottom: "15px",
  },
  label: {
    display: "block",
    marginBottom: "5px",
    fontWeight: "500",
    fontSize: "14px",
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #e5e7eb",
    borderRadius: "5px",
    fontSize: "14px",
    transition: "border-color 0.2s",
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #e5e7eb",
    borderRadius: "5px",
    fontSize: "14px",
    backgroundColor: "white",
  },
  textarea: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #e5e7eb",
    borderRadius: "5px",
    fontSize: "14px",
    minHeight: "80px",
    resize: "vertical" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    backgroundColor: "white",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    borderRadius: "8px",
    overflow: "hidden",
  },
  th: {
    backgroundColor: "#f3f4f6",
    padding: "12px",
    textAlign: "left" as const,
    fontWeight: "600",
    fontSize: "14px",
    borderBottom: "2px solid #e5e7eb",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #e5e7eb",
    fontSize: "14px",
  },
  trEven: {
    backgroundColor: "#f9fafb",
  },
  trHover: {
    transition: "background-color 0.2s",
    cursor: "pointer",
  },
  badge: {
    display: "inline-block",
    padding: "4px 8px",
    borderRadius: "9999px",
    fontSize: "12px",
    fontWeight: "500",
    backgroundColor: "#e5e7eb",
    color: "#374151",
  },
  badgeActive: {
    backgroundColor: "#10b981",
    color: "white",
  },
  badgeInactive: {
    backgroundColor: "#ef4444",
    color: "white",
  },
  alert: {
    padding: "12px",
    borderRadius: "5px",
    marginBottom: "20px",
  },
  alertSuccess: {
    backgroundColor: "#d1fae5",
    color: "#065f46",
    border: "1px solid #10b981",
  },
  alertError: {
    backgroundColor: "#fee2e2",
    color: "#ef4444",
    border: "1px solid #ef4444",
  },
  loading: {
    textAlign: "center" as const,
    padding: "40px",
    color: "#6b7280",
  },
  deleteConfirm: {
    backgroundColor: "#fee2e2",
    padding: "10px",
    borderRadius: "5px",
    marginTop: "5px",
  },
};
